channels:
  - conda-forge
  - defaults          # order matters: conda-forge searched first
dependencies:

  # Conda-forge / defaults packages
  - openbabel
  - rdkit
  - selfies
  - tqdm
  - vina==1.2.5
  - flask

  # PyPI-only packages
